### ISSUE TITLE
README instructions may not produce a working OpenOCD setup

### ISSUE THREAD

**Issue by ssokolow** [TeXitoi/blue-pill-quickstart#6]
My \*buntu setup already had a copy of OpenOCD installed in `/usr/local`, so following the instructions produced this error:

```
Open On-Chip Debugger 0.10.0+dev-00403-g3737dd69e738 (2018-04-20-22:55)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
embedded:startup.tcl:60: Error: Can't find openocd.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 60
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Error: Debug Adapter has to be specified, see "interface" command
embedded:startup.tcl:60: Error: 
in procedure 'script' 
at file "embedded:startup.tcl", line 60
```

The solution was to run this instead:

`openocd -f /usr/local/share/openocd/scripts/interface/stlink-v2.cfg -f /usr/local/share/openocd/scripts/target/stm32f1x.cfg`

It might be a good idea to acknowledge that possibility.

**Comment by TeXitoi** [comment]
The instructions say to launch openocd in the repository directory. Openocd should use the provided configuration file, and everything should work.

**Comment by ssokolow** [comment]
Ahh. I missed that.

Probably a good idea to make it more eye-catching given that the whole reason I made that mistake was because I'd opened a new tab to keep `openocd` from tying up the tab that was already in the repository directory.

(Also, `WARNING: interface/stlink-v2.cfg is deprecated, please switch to interface/stlink.cfg`)
